apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.service.name }}

spec:
  clusterIP: {{ .Values.service.clusterIP }}

  selector:
{{ .Values.labels | toYaml | indent 4 }}

  ports:
{{ .Values.service.ports | toYaml | indent 4 }}